pipeline:
  build:
    image: registry.pkgdev.rackspace.com/build-base:${DIST}
    commands:
      # Install build-deps
      - apt-get update
      - echo "yes" | mk-build-deps --install --remove debian/control
      # Set up the upstream branch - has to be orphan so the origin does not
      # include non-debian files.
      - git checkout --orphan upstream
      - git reset --hard
      # Add the upstream branch and get the archive
      - git remote add upstream https://github.com/rackerlabs/kthresher.git
      - git fetch -t upstream
      - git archive ${VERSION} -o ../kthresher_${VERSION}.orig.tar.gz
      - tar -zxf ../kthresher_${VERSION}.orig.tar.gz
      # Build, fetch origin debian dir and then build
      - git fetch --no-tags origin
      - git checkout $DRONE_COMMIT -- debian
      - debuild -us -uc --lintian-opts --profile debian
      # Rename deb
      - cd ..
      - rename "s/(.*)-(.*)\.deb/$1-${DIST}$2.deb/" *.deb

  upload-common:
    image: registry.pkgdev.rackspace.com/daf:dev
    aptlyurl: beast-internal.pkgdev.rackspace.com
    repo: common
    filename: ../kthresher_${VERSION}-${DIST}${RELEASE}_all.deb
    when:
      event: tag
      
  register-common:
    image: registry.pkgdev.rackspace.com/dar:dev
    aptlyurl: beast-internal.pkgdev.rackspace.com
    repo: common
    filename: kthresher_${VERSION}-${DIST}${RELEASE}_all.deb
    dist: ${DIST}
    when:
      event: tag

matrix:
  DIST:
    - bionic
    - xenial
    - trusty
    - debian-sid
    - debian-stretch
    - debian-jessie
  VERSION:
    - 1.3.1
  RELEASE: 
    - 1
